sudo: false
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '8'
env:
  - TZ="Europe/Brussels"
script:
  - npm test
cache:
  directories:
  - node_modules
os:
  - linux
  - osx
after_success:
  - npm run coverage
  - npm run report-coverage